export type User = {
  id: string,
  createdAt: string,
  salutation: string,
  firstName: string,
  fatherName: string,
  lastName: string,
  birthDate: null,
  isGroomOfRabbi: string | null,
  wifeBirthDate: null,
  husbandMobile: string,
  wifeMobile: string,
  whatsappNumber: string,
  systemPhone1: string,
  systemPhone2: string,
  email1: string,
  email2: string,
  homePhone: string,
  city: string,
  street: string,
  buildingNumber: string,
  entranceNumber: string,
  apartmentNumber: string,
  neighborhood: string,
  hasMarriedChildren: string,
  childrenAtHomeCount: number,
  wifeName: string,
  wifeIdNumber: string,
  idNumber: string,
  fullName: string,
  synagogue: string,
  role: 'user' | 'admin' | 'owner'
}
