//  {
//         "id": "ab920271-e03a-40b3-9600-a72b5de72c6a",
//         "created_at": "2025-09-14T16:04:42.228823+00:00",
//         "is_active": true,
//         "salutation": "הר\"ר",
//         "first_name": "חיים ישראל",
//         "father_name": "יואל",
//         "last_name": "אוירבך",
//         "id_number": "205370489",
//         "birth_date": null,
//         "wife_name": "רבקה ",
//         "is_groom_of_rabbi": null,
//         "wife_id_number": null,
//         "wife_birth_date": null,
//         "children_at_home_count": null,
//         "has_married_children": null,
//         "city": "ביתר עילית",
//         "street": "פחד יצחק",
//         "building_number": "21",
//         "apartment_number": "12",
//         "entrance_number": null,
//         "neighborhood": null,
//         "synagogue": "בית אהרן - ביתר",
//         "home_phone": "0527110602",
//         "husband_mobile": "0583281141",
//         "wife_mobile": null,
//         "whatsapp_number": null,
//         "system_phone_1": "0527110602",
//         "system_phone_2": null,
//         "email_1": "A0583281141@gmail.com",
//         "email_2": null,
//         "wants_to_register": false,
//         "husband_name": null,
//         "husband_father_name": null,
//         "full_name_search": "חיים ישראל אוירבך",
//         "city_lat": null,
//         "city_lon": null,
//         "street_lat": 31.7035064,
//         "street_lon": 35.1142175,
//         "coordinates": {
//             "lat": 31.7035064,
//             "lon": 35.1142175
//         }
//     },



export type User = {
  id: string,
  created_at: string,
  is_active: boolean,
  salutation: string,
  first_name: string,
  father_name: string,
  last_name: string,
  birth_date: null,
  is_groom_of_rabbi: null,
  wife_birth_date: null,
  husband_mobile: string,
  wife_mobile: string,
  whatsapp_number: string,
  system_phone_1: string,
  system_phone_2: string,
  email_1: string,
  email_2: string,
  home_phone: string,
  city: string,
  street: string,
  building_number: string,
  entrance_number: string,
  apartment_number: string,
  neighborhood: string,
  has_married_children: string,
  children_at_home_count: number,
  mother_name: string,
  wife_name: string,
  wife_id_number: string,
  husband_id_number: string,
  id_number: string,
  wife_email_1: string,
  wife_email_2: string,
  full_name_search: string,
  synagogue: string,
  notes: string,
  role: 'user' | 'admin' | 'owner'
}
    