import {
    pgTable,
    text,
    timestamp,
    real,
    bigserial,
    boolean,
    inet,
} from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
    id: text('id').primaryKey(),
    createdAt: timestamp('created_at'),
    salutation: text('salutation'),
    firstName: text('first_name'),
    lastName: text('last_name'),
    fatherName: text('father_name'),
    wifeName: text('wife_name'),
    wifeLastName: text('wife_last_name'),
    wifeFatherName: text('wife_father_name'),
    idNumber: text('id_number'),
    wifeIdNumber: text('wife_id_number'),
    birthDate: text('birth_date'),
    wifeBirthDate: text('wife_birth_date'),
    city: text('city'),
    street: text('street'),
    buildingNumber: text('building_number'),
    apartmentNumber: text('apartment_number'),
    entranceNumber: text('entrance_number'),
    neighborhood: text('neighborhood'),
    synagogue: text('synagogue'),
    homePhone: text('home_phone'),
    husbandMobile: text('husband_mobile'),
    wifeMobile: text('wife_mobile'),
    whatsappNumber: text('whatsapp_number'),
    systemPhone1: text('system_phone_1'),
    systemPhone2: text('system_phone_2'),
    email1: text('email_1'),
    email2: text('email_2'),
    wantsToRegister: text('wants_to_register'),
    husbandName: text('husband_name'),
    husbandFatherName: text('husband_father_name'),
    isGroomOfRabbi: text('is_groom_of_rabbi'),
    childrenAtHomeCount: text('children_at_home_count'),
    hasMarriedChildren: text('has_married_children'),
    fullName: text('full_name_search'),
    cityLat: real('city_lat'),
    cityLon: real('city_lon'),
    streetLat: real('street_lat'),
    streetLon: real('street_lon'),
    coordinates: text('coordinates'),
    password: text('password'),
    role: text('role'),
});

export const userLogins = pgTable('user_logins', {
    id: bigserial('id', { mode: 'number' }).primaryKey(),
    userId: text('user_id').notNull().references(() => users.id),
    loggedInAt: timestamp('logged_in_at', { withTimezone: true }).notNull().defaultNow(),
    ipAddress: inet('ip_address'),
    userAgent: text('user_agent'),
    success: boolean('success').notNull().default(true),
});

export type User = typeof users.$inferSelect;
export type UserLogin = typeof userLogins.$inferSelect;
