// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/users" | "/users/:id";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/protected-layout.tsx": {
    id: "routes/protected-layout";
    page: "/" | "/users" | "/users/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/users+/_layout.tsx": {
    id: "routes/users+/_layout";
    page: "/users" | "/users/:id";
  };
  "routes/users+/$id.detailes.tsx": {
    id: "routes/users+/$id.detailes";
    page: "/users/:id";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/login": typeof import("./src/routes/login.tsx");
  "routes/protected-layout": typeof import("./src/routes/protected-layout.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/users+/_layout": typeof import("./src/routes/users+/_layout.tsx");
  "routes/users+/$id.detailes": typeof import("./src/routes/users+/$id.detailes.tsx");
};